name: Test secrets

on: workflow_dispatch

jobs:
  process-paths:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add admin password to test.tfvars in 2 ways
        run: |
          sed -i 's/initial_dc_admin_password_secret = \"\"/initial_dc_admin_password_secret=\"${{ secrets.TESTSECRET }}\"\n/g' test.tfvars
          sed -i 's/initial_dc_admin_password_var = \"\"/initial_dc_admin_password_var=\"${{ vars.TESTVAR }}\"\n/g' test.tfvars
          cat test.tfvars
